{% set version = "1.7.4" %}

package:
  name: dicttoxml
  version: {{ version }}

source:
  fn: dicttoxml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dicttoxml/dicttoxml-{{ version }}.tar.gz
  sha256: ea44cc4ec6c0f85098c57a431a1ee891b3549347b07b7414c8a24611ecf37e45

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - dicttoxml

about:
  home: https://github.com/quandyfactory/dicttoxml
  license: GPL-2.0
  summary: 'Converts a Python dictionary or other native data type into a valid XML string. '
  license_family: GPL
  license_file: LICENCE.txt
  dev_url: https://github.com/quandyfactory/dicttoxml
  doc_url: https://github.com/quandyfactory/dicttoxml

extra:
  recipe-maintainers:
    - johanneskoester
    - jan-janssen
