travis:
  secure:
    BINSTAR_TOKEN: e56CxzKiCkFdgHj8LYGB0W41ujy3wULRyKzBOYe4jLYFiWKWeNpYqY3KrFKap4Ih4SHo7bmnRypUYq7WV9P8CauMKuhtksd33Jx4oa2sDarH9Cm8ZgE7p60AxxgilAlZIKcn5TVJfHCVfqAawypzBdFOGCBPpTxFJy8zVjvQjZNtqleQanSb0LIP9j5qoS7ouGdjpGedtCcIuDt2+FCRESI1ap4fnGTiLZpJwQkn6WJVIFtuMy98v9ABfE58Z7DKD6PU/pO7N1Isrd2CUIFVrzEIfVr6ozjb8Av5HEt+zPqpxuWmSJW4P0QO9hPjQM5iiryQSQR84zMbVkAQZYmhBoQ+hpICavNh0ThLJ1q1aKHWlex9vSQLqI4ddeFlmMQSsyJtwlJ29LbbcwW9xVEUOs2w7fzy21P3orE/BYkOHryqt0lEU+0EzWc4Q0Hqmuc2HknU032GewXt8oqCjLKwE+YjsjXrQYNp8S5zScTWjiraJLQFSRZWSX8amBoePobJO5kMgd/9PAZ+uVJJye1qg6V/Hvfs4DasX3yKQNAYApArXZfYrPJfDX/mSh9fpzQjRaqGqrEffc+Xncfg83eGgPPXJGkMpBf+Ob+LrNMuWyq5AHX9twzYlVfqO3hHzusz2S3VQNrBL71sBb0pSMx2ADMrErc5eYWZ95CmhpO0/pc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
